import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Blog() {
    return (
        <>
        <Head>
          <title>Quang Minh | Blog</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favIcon.png" />
        </Head>
        <NavBar/>
        
        </>
    )
}