import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const audioRef = useRef(null);
  
  const playPronunciationAudio = () => {
    audioRef.current.play();
  }

  return (
    <>
      <Head>
        <title>Quang Minh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favIcon.png" />
      </Head>
      <NavBar/>
      <div className="profile">
        <img 
          src="favIcon.png"
          width={150}
          height={150}
          className="profilePicture"
        />
        <div>
          <text className="profileText">
            Hi, I'm Quang Minh, but you can call me Minh.
          </text>
        </div>
        <div
          className="audioIcon"
          onClick={playPronunciationAudio}
        >
          <img
            width={15}
            height={15}
            src="audioIcon.png"
          />
          <div className="tooltipText">
            Press to hear pronunciation
          </div>
          <audio
            ref={audioRef}
            id="pronunciationAudio"
            src="namePronunciation.mp3"
          />
        </div>
      </div>
    </>
  )
}
