import Head from 'next/head'
import NavBar from '@/components/nav'

export default function Index() {
    return (
        <>
        <Head>
          <title>Peng</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/appstore.png" />        
        </Head>
        <NavBar/>
        <p style={{textAlign: 'center', color: "white", fontSize: 25, fontFamily: "sans-serif"}}>
        Your email has been successfully verified. Go back to the app and enjoy!
        </p>
        </>
    )
}