import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'
import Link from 'next/link'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function CatchUpBlog() {
    return (
        <>
        <Head>
          <title>Quang Minh | CatchUp</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/meInFutureUpScaled.jpeg" />        
        </Head>
        <NavBar/>
        <div className="main">
            <div className='blogsWrapper'>
            <div className='blog'>
                <div style={{marginTop: 30}}/>
                <text className="blogTitle">
                    CatchUp. Converse with you friends on a daily.
                </text>
                <text className="blogDate">
                    Sunday 22, January 2023
                </text>
            </div>
            <div className="blogImage">
              <img
                className="CatchUpScreenshot"
                src="/imgs/CatchUpScreenshot.png"
                width={300}
              />
            </div>
            <div className="blogText">
                <p>
                Everyday at a random time, everyone is sent a notification 
                asking them to write a little something to their friends.
                It could about anything. Your day, a funny thought you had, 
                that meal deal you had for lunch. Literally anything. You can only
                view your friend's posts once you've posted yours and you only have 
                2 hours to post. You can only post once per day, but you can continue 
                your conversations through comments.
                </p>
                <p>
                The point of this app is to encourage spontaneous conversations
                with your friends on a daily basis.
                </p>
                <hr></hr>
                <p>
                    This next bit describes the tech stack used in building the app. 
                </p>
                <p>
                    This app is built using React Native for UI, and Firebase for backend. 
                    I chose these two, because it significantly reduces development time.
                    Firebase offers firestore, a realtime NoSql database, which is really
                    useful
                    as when your friends creates a post, it instantly pops up on your feed.
                    The beauty is that this realtime listener can be done in few lines of code
                    using the onSnapshot() method. Firebase also handles authentication ie. 
                    storing passwords, emails. It also has methods that handles resetting passwords,
                    authenticating email, double factor auth. Again this is fantastic as these things
                    are necessary in almost every app (this one included).
                </p>
                <p>
                    It has a load of other built in features, which dramatically speeds up
                    development time and overall is a great product. However, it's hard to 
                    model relational data, and specifically hard if you have a lot of updates 
                    or writes to those relational data. The querying engine will fit the needs 
                    of most apps, but I don't think it's great if you have a lot of complex queries.
                    Another obvious disadvantage is you get tied down into the Google Cloud ecosystem.
                    And there's also risk of depending so heavily on a piece of for profit software.
                </p>
            </div>
          </div>
        </div>
        </>
    )
}