import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'
import Link from 'next/link'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function CatchUpBlog() {
    return (
        <>
        <Head>
          <title>
            Quang Minh | Leaving the market to operate freely is 
            the best way to move us to a low carbon, low pollution future
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/meInFutureUpScaled.jpeg" />        
        </Head>
        <NavBar/>
        <div className="main">
            <div className='blogsWrapper'>
            <div className='blog'>
                <div style={{marginTop: 30}}/>
                <text className="blogTitle">
                    Leaving the market to operate freely is 
                    the best way to move us to a low carbon, low pollution future
                </text>
                <text className="blogDate">
                    Thursday 25, February 2021
                </text>
            </div>
            <div className="blogText">
                <p>
                    A rules based free market system combined with a stable
                    governing body, has led to extraordinary improvements in
                    quality of life for the human race. Throughout the past
                    120 years, we had a pandemic that killed 50 million,
                    two world wars with 70 million in casualties,
                    the great depression and a sizable percentage of people
                    living under a communist economic system for some time.
                    Yet global GDP rose from 3.4 trillion in 1900 to 87 trillion dollars today.
                    However, these improvements in quality of life have not come about without a cost.
                    That cost is global warming, which comes in the form of extreme weather
                    damages (hurricane,floods), loss of coastal real estate, respiratory and 
                    lung diseases related to pollution, oil and gas spills and many more. 
                    At a conservative estimated social cost of $35 per tonne of CO2 equivalents emitted,
                    that works out to be $1.75 trillion hit to the global economy every year.
                </p>
                <p>
                    These costs are a result of energy generation and use via burning
                    and extraction of fossil fuels such as oil, coal and natural gas,
                    which emits large amounts of harmful greenhouse gasses into the
                    atmosphere in both of these processes. If the world continues
                    to emit greenhouse gasses at the current rate of 51 billion
                    tonnes of CO2 equivalents per year or more well into the next few decades,
                    the costs mentioned above may balloon to multiple times the current rate,
                    creating extreme economic,environmental and social costs.
                </p>
                <p>
                    Transportation
                </p>
                <p>
                    The free market has characteristics that make it attractiv
                    as a way to help reduce emissions. Firstly, markets provide
                    a signal which shows firms and entrepreneurs that there is
                    a high potential return on capital to be made and this
                    incentivises them to enter the industry. Competition is also
                    another factor, as firms want to maximise profits, 
                    they find all sorts of ways to improve the product or service
                    and lower the cost. These two functions of markets can
                    help drive us to a sustainable future. 
                </p>
                <p>
                    An example of free markets driving down costs that
                    helps reduce emissions is in lithium ion production which has
                    seen a near 86% reduction in price from $1160 per Kwh in 2010 to
                    $156 per Kwh in 2019 caused largely by increased production benefiting
                    from economies of scale and R&D spending because of rising demand for EV.
                    This is particularly significant as lithium ion batteries traditionally make
                    up 30-60% of an electric vehicle’s cost of production and it doesn’t look
                    like this trend of improvement in price is stopping anytime soon as
                    producers continue to expand capacity to cope with increasing 
                    demand from the EV market. Consensus amongst so-called 
                    experts believe that at $100 per kwh, electric vehicles will cost
                    the same to manufacture and sell (at the same margin) as ICE vehicles. 
                </p>
                <p>
                    The leader in mid to high end ev market is Tesla Inc, which although
                    unprofitable(excluding regulatory credit sales), boasts a gross profit
                    margins of 24% for fiscal year 2020 which is impressive when compared to
                    other manufacturers such as Toyota’s 20%  which produces 8.8 million vehicles
                    compared to Tesla’s 500,000. When compared to GM, Ford and Volkswagen it also
                    shows a similar situation.
                </p>
                <p>
                    These profitability signals and trends of decreasing prices
                    incentivise entrepreneurs and traditional automakers to enter
                    the market despite EVs being only a small portion of global
                    auto sales as they see there is money to be made in the future
                    as consumers switch from ICE to electric. This is promising
                    as the transportation sector accounts for roughly 16% of 
                    greenhouse gas emissions with 11% coming from road transports.
                </p>
                <p>
                    Although the free market played a huge role in reducing average
                    costs of batteries and electric cars through increased scale, 
                    this would have not happened if it weren’t for government subsidies
                    on EV sales of sometimes up to $9800 per vehicle or 30% of vehicle
                    price which is paid to manufacturers or customers (depending on specific policies),
                    that incentivised firms and entrepreneurs to enter the EV market in the first place.
                </p>
                <p>
                    Governments around the world have also introduced tax rebates,
                    grants and loans to help firms develop lower cost electric vehicles.
                    They have also provided financial aid to help build out electric charging
                    stations infrastructure. The Chinese government for example has
                    also put more regulatory burden on internal combustion engine factories
                    requiring them to have a certain amount of capacity for electric motors.
                </p>
                <p>
                    These policies have also been specifically structured to incentivise
                    for higher performance. In China for example, subsidies for EVs with a 
                    range above 400km will be $3900 per vehicle and $2900 for vehicles between
                    a range of 250 to 400km.
                </p>
                <p>
                    Energy generation
                </p>
                <p>
                This trend of increased production causing reduction in prices are also happening with solar and to a lesser degree with wind which has seen its levelized cost of energy reduce from $135 mwh to $42 mwh and solar $359 mwh to $43 mwh from 2009 to 2018 as global cumulative solar pv has gone from 50 gigawatts to above 500 gigawatts in the same period. This means that with increased output, average costs go down dramatically because of economies of scale.
                </p>
                <p>
                    Government policy has also played a huge role in this sector as well, especially the Chinese government which introduced aggressive feed-in-tariffs in 2010 which are contracts to renewable energy producers in which compensation is determined by cost per mwh or kwh which incentivises cost improvements. From the time those subsidies were first introduced to today, in China the cumulative installed PV measured in Gigawatts has increased more than 200 fold and the market share from Chinese firms has increased from almost less than 1% to 55% of global cumulative PV capacity. This shows that government policy can have a drastic impact on markets. Although this growth in absolute terms is phenomenal for China and the world, energy consumption from renewables still only accounts for 16%.
                </p>
                <p>
                    Although governments and firms are going full speed towards renewable energy, the main way we get energy is still from fossil fuels. Coal and natural gas power plants still account for 60% of global electricity generation and when considering all energy consumption (electricity generation + transport) that number goes to 84% with 33% attributable to oil. With rising demand from emerging markets such as India and China combined with increases in efficiencies still happening in the oil and gas sector, it’s hard to see how without government intervention, we can move ourselves towards a low carbon future in time.
                </p>
                <p>
                    Take the shale oil production boom in America as an example of free markets driving down the prices of energy and fuel, which is great for consumers, but terrible for the environment. Through the use of new drilling techniques and low interest rates, production costs fell dramatically and investors piled in money creating a massive increase in supply. In 2014 oil production in the US averaged 8.8 million barrels a day in 2020 even in a severe recession that saw oil futures go negative, US production was 11.3 million a day. These activities hurt the environment in two ways. Firstly, hydraulic fracturing produces methane which is multiple times more potent than CO2 and this drilling uses a lot of water which can get contaminated as it gets pumped out of the ground and some finds its way back into water sources. Secondly, hydraulic fracturing also played a role in increasing the supply of natural gas (shale gas) which helps decrease the price of it, this is not great as natural gas is one of the main competitors against renewables in electricity generation.
                </p>
                <p>
                    This is an example of free market mechanisms working great for consumers providing lower prices, but against a low carbon future.
                </p>
                <p>
                    Government policy in this sector has also not been great as producers have constantly gotten away without paying for the externalities that they cause which comes mainly in the form of CO2 emissions. The oil, gas and coal sector whilst not paying their fair share for the negative externalities that they create, have even gotten subsidies from governments. For example, The International Institute for Sustainable Development estimates that the total subsidies given to Chinese coal sector was $18 billion in 2015 alone’. Favorable policies that only benefit the oil and gas sector also still exist all over the world. For example in the U.S, the Master Limited Partnership structure allows companies to be exempt from corporate tax and get the benefits of being a public company which allows easy access to capital (limited partners or shareholders still pay personal income tax on dividends). This structure is prohibited for renewable energy companies.
                </p>
                <p>
                Steel, cement and livestock (7.2%,3%,6% of greenhouse gas emissions)
                </p>
                <p>
                The problem with the steel industry does not have to do with governments or free markets. It has to do with the fact that right now there is no alternative to producing these materials on a large scale, without using coal. And these materials play a crucial role in the economy where you simply cannot stop production. In this scenario, the only real solution is for governments to incentivise research into new production techniques that don’t use coal and can become economically reasonable i.e. cost competitive to traditional methods. This is also the same problem facing a low carbon future in the cement industry. This is worrying as they account for 10% of emissions but have no real clean alternative right now.
                </p>
                <p>
                The meat industry (beef accounts for almost all emissions) on the other hand is getting disrupted by plant based meat providers such as Beyond Meat and Impossible burger which have seen their market share increase dramatically albeit from a small base. Innovation is also happening in the lab grown meat sector, which in December saw the Singapore food agency announce regulatory approval for the sale of lab grown meat for the first time. The prices of these products, whilst a lot higher compared to real meat, have been falling dramatically over the past few years. For example in 2013 lab grown meat cost $280,000 for one beef burger now the cost to produce one kilogram is around $100. This improvement is actually not due much to increased scale, but rather high R&D spending by private companies. This is the opposite when looking at plant based meat as production has gone up dramatically and average cost of production has gone down due to benefits from economies of scale. Whilst the prices of these products are still double or triple that of real beef, there will still be big cost improvements in the future. Free market signals such as massive increases in revenues are present in this field also. Beyond Meat for example had revenues of $16 million in 2016 but in the last 12 months, they recorded more than $400 million. Governments have also helped out here, mainly in the form of R&D spending which have helped improve the technology.
                </p>
                <p>
                Overall, leaving the free market to operate on its own would be suicidal, because there would be zero incentives to get rid of negative externalities and emissions will only grow. This means that it’s down to policy makers to aggressively incentivise markets to transition towards sustainable development and then free markets would take care of the rest. 
                </p>
                <p>
                A good example is electric vehicles, where governments like China and America have given all sorts of subsidies,loans,grants and tax rebates. These financial incentives trigger a signal to the market that money can be made in this sector. What happened next was a bunch of private companies entering the market both to produce lithium ion batteries and electric vehicles. As a result prices went down massively, because of economies of scale and increased competition. In the near future, battery prices will be so low and hence electric vehicles will cost less to manufacture than ICE vehicles that governments wouldn’t need to subsidize them anymore.                      
                </p>
                <p>
                The combination of free markets and good government policies has worked well in the past, I'm sure they won't disappoint in the future. As the old proverb goes, “It takes two to tango”.
                </p>
              </div>
          </div>
        </div>
        </>
    )
}