import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'

import { useRef, useEffect } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function BlogPage() {
    return (
        <>
        <Head>
          <title>Quang Minh | Blog</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/meInFutureUpScaled.jpeg" />        
        </Head>
        <NavBar/>
        <div className="main">
          <div className="blogsWrapper">
            <div className='container'>
              <div className='blog'>
                  <div style={{marginTop: 30}}/>
                    <Link href="blogs/whatchadoinn" style={{ textDecoration: 'none', padding: 0 }}>
                      <text className="blogTitle">                        
                        Peng
                      </text>
                    </Link>
                    <text className="blogDate">
                      Saturday 1, April 2023
                    </text>
              </div>
              <div className='blog'>
                  <div style={{marginTop: 30}}/>
                    <Link href="blogs/catchUp" style={{ textDecoration: 'none', padding: 0 }}>
                      <text className="blogTitle">
                        CatchUp. Converse with you friends on a daily.
                      </text>
                    </Link>
                    <text className="blogDate">
                      Sunday 22, January 2023
                    </text>
              </div>
              <div className='blog'>
                <div style={{marginTop: 30}}/>
                <Link href="blogs/joyy" style={{ textDecoration: 'none', padding: 0 }}>
                  <text className="blogTitle">
                    Undervalued social media
                  </text>
                </Link>
                <text className="blogDate">
                  Sunday 11, December 2022
                </text>
              </div>  
              <div className='blog'>
                <div style={{marginTop: 30}}/>
                <Link href="blogs/rcmt" style={{ textDecoration: 'none', padding: 0 }}>
                  <text className="blogTitle">
                    RCM Technologies. Mispriced mini conglomerate
                  </text>
                </Link>
                <text className="blogDate">
                  Sunday 11, December 2022
                </text>
              </div>
              <div className='blog'>
                <div style={{marginTop: 30}}/>
                <Link href="blogs/econ-essay" style={{ textDecoration: 'none', padding: 0 }}>
                  <text className="blogTitle">
                    Leaving the market to operate freely is 
                    the best way to move us to a low carbon, low pollution future.
                  </text>
                </Link>
                <text className="blogDate">
                  Thursday 25, February 2021
                </text>
              </div>
            </div>           
          </div> 
        </div>
      </>
    )
}