import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'
import Link from 'next/link'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function JoyyBlog() {
    return (
        <>
        <Head>
          <title>Quang Minh | Joyy</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favIcon.png" />
        </Head>
        <NavBar/>
        <div className="main">
            <div className='blogsWrapper'>
            <div className='blog'>
                <div style={{marginTop: 30}}/>
                <text className="blogTitle">
                    Undervalued social media
                </text>
                <text className="blogDate">
                    Sunday 11, December 2022
                </text>
            </div>
            <div className="blogText">
                <p>
                Time of purchase: 21/04/2022
                </p>
                <p>
                    As of 21/04/2022
                    <br/>
                    Market cap: $2,656,500,000
                    <br/>
                    Net debt: - $3,718,000,000
                    <br/>
                    Enterprise value: - $1,061,150,000
                    <br/>
                </p>
                <p>
                    Share price at time of purchase: $37.50
                    <br/>
                    Share price as of 11/12/2022: $35.00
                </p>
                <p>
                    JOYY Inc is a social media company operating 
                    apps like Bigo Live, which allows users to live
                    stream specific moments, such as showcase talents,
                    socialize and connect with other users worldwide. 
                    This Bigo Live is JOYY’s biggest asset with average
                    mobile monthly active users (MAUs) of 35.4 million. 
                    It also owns Likee, a short form video platform which 
                    has average MAUs of 50 million, and Hago a casual game
                    orientated social media platform with instant messaging features
                    and video calls. This app has MAUs of 7.6 million.
                </p>
                <p>
                    JOYY is extremely undervalued if you just look at the items
                    on its balance sheet.
                </p>
                <p>
                    As of September 2022, JOYY had a net asset value of $5.8 billion
                    with $4.2 in cash and a cash - total liabilities of $1 billion.
                </p>
                <p>
                    Revenues for the Bigo Live business in year-end 2021 was $2.4 billion 
                    with a GAAP net loss of 80 million.
                </p>
                <p>
                    For reference, internet companies operating in the entertainment space often
                    are valued at 1x - 5x revenues and at least 2x net asset value.
                </p>
                <p>
                    If we take into consideration that the company is selling at ~0.5x of net asset
                    value, the massive cash cushion it has and the fact that it’s valued at the lower 
                    end of the industry from a revenues perspective, then we can see that this business
                    is being undervalued by the market. Management seems to agree with this assessment as
                    they’ve announced a $1 billion dollar buyback program in November 2021. Which is 
                    approximately 38% of the value of the company. In September 2019 JOYY also announced
                    a $300 million buyback program, which was completed as planned a year later. 
                    As well as this, on the 27th of August 2021 Reuters reported an exclusive article saying
                    that management had intentions of taking the company private at a valuation of $8 
                    billion, as the market price is undervaluing JOYY. Although this was taken from a private source
                    , it still reinforces the valuation we’ve done today.
                </p>
                <p>
                    If we take a look at financial valuations and actions that management has taken,
                    then we can come to a conclusion that the market is undervaluing the fair value of this business.
                </p>
            </div>
            </div>
        </div>
        </>
    )
}