import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'
import Link from 'next/link'

import { useRef, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function JoyyBlog() {
    return (
        <>
        <Head>
          <title>Quang Minh | RCMT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favIcon.png" />
        </Head>
        <NavBar/>
        <div className="main">
            <div className='blogsWrapper'>
            <div className='blog'>
                <div style={{marginTop: 30}}/>
                <text className="blogTitle">
                    RCM Technologies. Mispriced mini conglomerate
                </text>
                <text className="blogDate">
                    Sunday 11, December 2022
                </text>
            </div>
            <div className="blogText">
                <p>
                    Time of write up: 11/12/2022
                    <br/>
                    Time of purchase: 03/12/2020
                    <br/>
                    Time of disposal: 11/02/2021
                    <br/>
                </p>
            As of 03/12/2020
            <br/>
            Market Cap: $19,014,492
            <br/>
            Net debt (cash & cash equivalents - total debt): $10,000,000
            <br/>
            Enterprise Value: $29,014,492
            <br/>

            Share price at time of purchase: $1.64
            <br/>
            Share price at time of disposal: $9.90
            <br/>

            <p>
                There are a couple of things that made RCM 
                Technologies a very attractive investment at 
                a market cap of $19,014,492.
            </p>
            <p>
            Company description, financial performance and valuation.
            </p>
            <p>
            The company is a mini conglomerate, owning three unrelated businesses.
            </p>
            <p>
                1) Specialty healthcare staffing.
            </p>
            <p>
                This business provides healthcare staffing services, connecting 
                healthcare professionals such as therapists, nurses, caregivers,
                etc with large government entities such as the New York Board of Education.

                For the period 2012-2019 revenues in this segment grew by 19% compounded
                annually (CAGR). With revenues at the end of year 2019 at $83 million and
                producing ~$6.9 million in EBITDA(Earnings before interest, taxes, depreciation and amortization). 

                AMN, a bigger competitor, trades at ~12-14x EBITDA and is a much slower growing
                business with revenues growing at ~ 12% (CAGR) in the same period.

                Assuming a worst case scenario where the market values this segment
                at 8x EBITDA then we can assign ~$41 million to this segment.

                Base case 10x EBITDA = $69 million

                Best Case 12x EBITDA = $82 million.
            </p>
            <p>
             2) Engineering services
            </p>
            <p>
            This segment provides a wide range of engineering services such as:

            Project Management Engineering & Design, Engineering Analysis, Engineer-Procure-Construct,
            Configuration Management, Hardware/Software Validation & Verification, Quality Assurance, 
            Technical Writing & Publications, Manufacturing Process Planning & Improvement and 3D/BIM Integrated Design. 
            Engineering services are provided at the site of the client or at the Company’s own facilities.

            From the period 2012-2019, sales of this segment have averaged $79 million with average EBITDA at $5.2 million.
            The reason I’ve taken average instead of looking at growth rate is the nature of this business is volatile, 
            as the timing of contracts are irregular and contract size as a percentage of revenues are quite large.

            Hill International, Inc is a competitor operating in the same industry and it currently sells at 0.75x of sales.
            Once again if we value this segment at a conservative 

            0.5x of sales we get a valuation of ~$39 million.
            </p>
            <p>
            3) IT & Life Sciences
            </p>
            <p>
            The Company’s Life Sciences and Information Technology segment is an integrated
            group of business units providing staff supplementation services and project solutions
            with physical locations in the United States, Canada and Puerto Rico primarily supporting
            Financial, Technical, Manufacturing, Life Sciences and Distribution applications.
            Specialization in project solutions include, but are not limited to, the following areas:
            </p>
            <p>
            ●
                Life Sciences: Specializes in providing innovative options to pharmaceutical,
                medical device and biotechnology companies in need of guidance, support or 
                remediation of quality, compliance or business challenges. 
                The group assists in staffing, solution planning and remediation needs in
                the areas of automation, compliance, data analytics, technical quality assurance
                and management, and validation and verification.
            </p>
            <p>
            ●
                IT Services & Solutions: Global provider of business and
                technology solutions designed to improve the operational 
                performance of our clients. Specialties include software development, 
                infrastructure services, and managed IT solutions.  
                The Company has a 40-year history of providing qualified IT candidates
                to customers in a timely and cost-effective manner to address their 
                specific business needs. The Company offers scalable solutions 
                that can provide emerging growth companies with a single qualified 
                resource or an entire project team along with RCM’s project management
                oversight to Fortune 100 clients
            </p>
            <p>
                This segment’s revenues have been declining YoY
                for the period 2012-2019 and over that time frame
                has an average EBIT of ~$1.59 million.
            </p>
            <p>
                For the sake of simplification I’ll assign $0 
                to this business segment.
            </p>
            <p>
                In combination.
            </p>
            <p>
                Valuation cases.
            </p>
            <p>
                Worse case: $70 million (41 + 39 - 10)
                <br/>
                Base case: $98 million (69 + 39 - 10)
                <br/>
                Best case: $111 million (82 + 39 - 10)
            </p>
            <p>
                Large Insider buying
            </p>
            <p>
            In early June 2020, the company, the CEO, CFO, and a 
            board member purchased a block of just under 3mm shares
            of RCMT from M2O, the family office that had previously 
            been the largest shareholder of the company (and a backer
            of the CEO’s activism on the company).  RCMT repurchased
            1.86mm shares, the CEO purchased 850k shares, the CFO purchased
            150k shares, and a board member purchased 100k shares.  
            The price for all purchases was $1.20 per share.
            These are possible signs that management thinks that the 
            company is of a good value at this price range.
            </p>
            <p>
                Conclusion
            </p>
            <p>
                So here we have a business that has no risk of bankruptcy
                or material decline in the value of the company, selling
                at a worse case scenario of 28% of the actual value of the company.

                There’s also consensus action from management confirming 
                the undervaluation as they’ve purchased roughly 27% of the company.

                These actions reinforce the valuations that I’ve made 
                and the potential return here is more than 260%, depending on
                the timeframe that the market will revalue this business to a more
                appropriate level that reflects the fair value of the business.
            </p>
            </div>
        </div>
        </div>
        </>
    )
}