import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/nav'

export default function WhatChaDoinn() {
    return (
        <>
        <Head>
          <title>Quang Minh | WhatChaDoinn</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/meInFutureUpScaled.jpeg" />        
        </Head>
        <NavBar/>
        <div className="main">
            <div className='blogsWrapper'>
                <div className='blog'>
                    <div style={{marginTop: 30}}/>
                    <text className="blogTitle">
                        WhatChaDoinn?
                    </text>
                    <text className="blogDate">
                        Sunday 26, March 2022
                    </text>
                </div>
                <div class="app-icons">
                    <a href='https://apps.apple.com/us/app/whatchadoinn/id6446037266'
                        target="_blank"
                    >
                        <img
                            alt='Get it on App store'
                            style={{width: 136, height: 58}}
                            src="/imgs/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg"
                        />
                    </a>
                    <a href='https://play.google.com/store/apps/details?id=com.whatchadoinn'
                        target="_blank"
                    >
                        <img 
                            alt='Get it on Google Play' 
                            style={{width: 150, height: 58}}
                            src='https://play.google.com/intl/en_gb/badges/static/images/badges/en_badge_web_generic.png'
                        />
                    </a>
                </div>
                <div className="blogText" >
                    <p>Ever wanted to know what exactly
                        your friend is up to this exact second?
                        Well, send them a WhatChaDoinn!
                    </p>
                </div>
                <div>
                    <img
                        src="/imgs/screenshot_askWhatFriendsAreUpTo-removebg-preview.png"
                        width={300}
                    />
                </div>
                <div className='blogText'>
                    <p>
                        A notification will be sent to them and they'll have 7 minutes to take a photo 
                        of what exactly they're up to.
                    </p>
                </div>
                </div>
            </div>
        </>
    )
};